<img src="../images/no-norm-image-embeds.png">

In [1]:
import numpy as np

a = np.array([0.3, 1])
b = np.array([0.4, 1.3])
c = np.array([10, 1])

Calculate dot product between these.

In [2]:
a @ b  # these are the most similar

1.42

In [3]:
a @ c  # c is the radio...

4.0

In [4]:
b @ c  # the magnitude of c gives it a high dot product

5.3

### Normalization Helps

Normalization helps us remove magnitude as a factor (because all vectors are given the same magnitude).

In [5]:
a = a / np.linalg.norm(a)
b = b / np.linalg.norm(b)
c = c / np.linalg.norm(c)
a, b, c

(array([0.28734789, 0.95782629]),
 array([0.29408585, 0.95577901]),
 array([0.99503719, 0.09950372]))

In [6]:
a @ b  # these now have a high dot product

0.9999752042549461

In [7]:
a @ c  # c is not so similar anymore

0.38122911022229045

In [8]:
b @ c  # also here

0.38772992263784645