[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/pinecone-io/examples/blob/master/learn/search/image/image-retrieval-ebook/cnn/xx_saturation.ipynb) [![Open nbviewer](https://raw.githubusercontent.com/pinecone-io/examples/master/assets/nbviewer-shield.svg)](https://nbviewer.org/github/pinecone-io/examples/blob/master/learn/search/image/image-retrieval-ebook/cnn/xx_saturation.ipynb)

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

def relu(x):
    return np.maximum(0, x)

In [4]:
inputs = np.asarray([3.1, -4.5, 0.8, -2.7, 4.9])

In [5]:
sigmoid(inputs)

array([0.95689275, 0.01098694, 0.68997448, 0.06297336, 0.99260846])

In [6]:
tanh(inputs)

array([ 0.99594936, -0.99975321,  0.66403677, -0.99100745,  0.9998891 ])

In [7]:
relu(inputs)

array([3.1, 0. , 0.8, 0. , 4.9])